M48
; DRILL file {KiCad 8.0.1} date 2024-10-21T20:58:11+1300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-21T20:58:11+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X111.469Y-68.3
X116.319Y-68.3
T2
X111.169Y-65.27
X116.619Y-65.27
M30
